trigger: none

extends:
    template: /eng/pipelines/templates/stages/archetype-sdk-tests.yml
    parameters:
      Location: westus2
      PackageName: "@azure/identity"
      ServiceDirectory: identity
      TimeoutInMinutes: 120
      PersistOidcToken: true
      CloudConfig:
        Public:
          SubscriptionConfigurations:
            # Contains alternate tenant, AAD app and cert info for testing
            - $(sub-config-identity-test-resources)
            - $(sub-config-identity-test-resources-js)
      AdditionalMatrixConfigs:
        - Name: Identity_msi_live_test_base
          Path: sdk/identity/identity/managed-identity-matrix.json
          Selection: sparse
          GenerateVMJobs: true
      MatrixReplace:
        - Pool=.*LINUXNEXTPOOL.*/azsdk-pool-mms-ubuntu-2204-identitymsi
        - OSVmImage=.*LINUXNEXTVMIMAGE.*/azsdk-pool-mms-ubuntu-2204-1espt
      PreSteps:
        - pwsh: |
            [System.Convert]::FromBase64String($env:PFX_CONTENTS) | Set-Content -Path $(Agent.TempDirectory)/test.pfx -AsByteStream
            Set-Content -Path $(Agent.TempDirectory)/test.pem -Value $env:PEM_CONTENTS
          env:
            PFX_CONTENTS: $(PFX_CONTENTS)
            PEM_CONTENTS: $(PEM_CONTENTS)
      EnvVars:
        AZURE_CLIENT_ID: $(IDENTITY_SP_CLIENT_ID)
        AZURE_CLIENT_SECRET: $(IDENTITY_SP_CLIENT_SECRET)
        AZURE_TENANT_ID: $(IDENTITY_SP_TENANT_ID)
        IDENTITY_PEM_CONTENTS: $(PFX_CONTENTS)
        IDENTITY_SP_CERT_PEM: $(Agent.TempDirectory)/test.pem
